# Generated by Django 5.1.2 on 2024-11-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='datetime',
            new_name='dateetime',
        ),
    ]
